# vim:fileencoding=utf-8:foldmethod=marker

scrollback_lines 10000

include current-theme.conf

font_family     FiraCode Nerd Font Mono
font_size       14.0
window_margin_width     10
background_tint         0.97
background_tint_gaps    -10.0
window_border_width     1pt
active_border_color     #44ffff
single_window_margin_width 0
confirm_os_window_close 1

enabled_layouts Tall, *
macos_option_as_alt yes
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard
map f1 launch --type=overlay sh -c 'cat ~/.config/kitty/cheatsheet; printf "\n"; read -r _'
map f2 launch --type=background --cwd=current lite-xl .
map f3 new_window_with_cwd
map f4 close_window_with_confirmation
map f5 load_config_file
map f6 new_tab_with_cwd
map f7 next_tab
map f8 close_tab

tab_bar_style       powerline
tab_powerline_style slanted

include local.conf
